apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: appgw-containers
  namespace: azure-alb-system
spec:
  associations:
  - /subscriptions/9adde229-f7bd-48c4-9c15-13737b234917/resourceGroups/rg-aks-agc-demo/providers/Microsoft.Network/virtualNetworks/vnet-aks-agc/subnets/subnet-appgw
  resourceRef:
    resourceId: /subscriptions/9adde229-f7bd-48c4-9c15-13737b234917/resourceGroups/rg-aks-agc-demo/providers/Microsoft.ServiceNetworking/trafficControllers/appgw-containers
